@token = ""
@displayName = "default"
@objectId = ""

POST https://graph.microsoft.com/v1.0/applications/{{objectId}}/addPassword
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}

{
    "passwordCredential": {
        "displayName": "{{displayName}}"
    }
}